# fly.toml app configuration file generated for seedcase-deploy on 2023-12-19T14:33:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "seedcase-deploy-pr"
primary_region = "arn"
swap_size_mb = 512

[build]
  # image = "philter87/django:ci"
  dockerfile = "Dockerfile"

[env]
  PORT = "10000"

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="seedcase_persistence_pr"
  destination="/app/persistence"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
