name: Continuous Integration Seedcase
run-name: CI for Seedcase
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting CI pipeline ${{ github.event_name }}, ${{ runner.os}}, ${{ github.ref }}, ${{ github.repository }}"
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          image: philter87/django
          tags: 0.0.1, latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
