name: Continuous Integration Seedcase
run-name: CI for Seedcase
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World! ${{ github.event_name }}, ${{ runner.os}}, ${{ github.ref }}, $ {{ github.repository }}"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: false
      - name: Install dependencies
        run: poetry install